* Интро

Шпаргалка по теории вероятности.

* Термины и понятия

** Вероятностное пространство
Cостоит из омеги - всех возможных
исходов, симгмы-алгебры подномжества омеги, называемых событиями -
т.е. те исходы, которые реально могут свершиться (например, машина может
завестить или не завестись, но мы не рассчитываем, что на нее свалится
метеорит), и веростностной меры - это означает, что сумма вероятностей
всех исходов должна равняться единице - т.е. 100%.

** Ассоциативня операция
Это операция, которую можно выполянть над
элементами в том порядке, в котором мне удобно, опустив скобки, и
результат при этом не изменится. Напримр, сложение: (1 + 2) + 3 = 1 +
2 + 3.

** Нейтральный элемент
Это такой элемент, используя который с ассоциативной операцией и другими
элементами, мы не изменим результат от выполнения ассоциативной
операции. Например, 0 + 1 + 2 + 0 + 3 = 1 + 2 + 3. Поэтому ноль для
сложения - это нейтральный элемент, как единица для умножения.

** Обратный элемент
Это такой элемент, что если взять его и его парный элемент и применить
над ними ассоциативную операцию, то получится нейтральнй
элемент. Например, 1 + (-1) = 0. Т.е. -1 является обратным элементом для
единицы при условии, что в качестве ассоциативной операции у нас
сложение.

** Математическая группа
Математическая группа - это некое множество - т.е. набор каких-то
объектов, - которые обладают нейтральным элементом, обратным элементом и
ассоциативной операцией.

** Несовместные события
Это такие события - вершившиеся исходы - из которых может в рамках одного
эксперимент исполниться только одно. Например, машина либо заведется,
либо не заведется. Но она не может завестить или не
завестисьодновременно.

** Зависимые события

Это такие события,где наступление одного события влияет на наступление
другого события. Например, машине не едет, потомучто нет бензина.
** Независымые события

Это такие события, где наступление одного события не влияет на
наступление другого события. Например, подбрасывание монетки: если в
прошлый раз выпал орел, то в этот раз тоже может выпасть орел, а может и
решка.
** Апостериорная вероятность
Это условная вероятность случайного события при условии того, что есть
данные, полученные в следствие опыта.

** Априорная вероятность
Это условная вероятность случайного события при условии того, что
экспериментальные данные еще не учтены.
Это та самая "интуитивная" вероятность, на которую обычно опираются люди,
когда оценивают вероятность какого-то события исходя из личного опыта, а
не из рассчеттов.

* Формула полной вероятности
Позволяет вычислить вероятность интересующего события через условные
вероятности этого события в предположении неких гипотез, а также
вероятностей этих гипотез.

см.
https://ru.wikipedia.org/wiki/%D0%A4%D0%BE%D1%80%D0%BC%D1%83%D0%BB%D0%B0_%D0%BF%D0%BE%D0%BB%D0%BD%D0%BE%D0%B9_%D0%B2%D0%B5%D1%80%D0%BE%D1%8F%D1%82%D0%BD%D0%BE%D1%81%D1%82%D0%B8

Дано вероятностное пространство и полная группа попарно несовместных
событий такие что:
- вероятность свершения любого события > 0
- из двух попарно несовместных событий может свершиться только одно:
  т.е. при событиях i и j, которые не равны друг другу, пересечение
  вероятностей свершения этих события образуют пустое множество
- все события от i до n образуют все возможные исходы

Говоря человеческим языком это означает, что в множестве представленных
исходов все имеют какие-то шансы свершиться - т.е. машина либо заводится,
либо нет. Но мы не думаем, что ее может раздавить тирекс. И в случае
противоположных исходов может свершиться только один из них: машина либо
заводится, либо нет.

Как посчитать вероятность какого-то события по формуле полной
вероятности?

Формула звучит так: вероятность события А, принадлежащего к возможным
событиям в рамках эксперимета, которое может произойти совместно только с
одним событием Вi высчитывается как сумма произведений вероятностей
гипотез на условные вероятности события, вычисленные соотвественно при
каждой из гипотез.

В переводе на русский это означает, что:
- сначала вычисляются вероятности каждой из гипотез (например,
  вероятность того, что машина заведется и не заведется)

- затем вычисляем вероятность свершения события при условии, что
  сработает какая-то из гипотез - т.е. какова вероятность того, что
  свершится событие Аi, если вершилось событие Вi

- перемножаем вероятность свершения события Вi - это обозначается как
  P(Вi) - и условную вероятность того, что событие Аi свершится при
  свершении события Вi - это обозначается как P(А|B)

- повторяем предыдущие пункты для всех событий Аi и Bi

- складываем полученные произведения


** Задача 1
Из 40 деталей 10 изготовлены в первом цехе, 25 — во втором, а остальные —
в третьем. Первый и третий цехи дают продукцию отличного качества с
вероятностью 0.9, второй цех — с вероятностью 0.7. Какова вероятность
того, что взятая наудачу деталь будет отличного качества?

*** Решение
Всего 40 деталей, они все перемешаны в общем ящике. Если привести задачу
к формуле, то получается, что верояность наступления события А - это
вытащить деталь надлежащего качества (что мы и ищем), а вероятность
наступления события В - это вытащить деталь, проивезеденную в первом,
втором или третьем цеху.

Делаем по формуле. Сначала считаем вероятности натсупления событий Вi.
Получается, что вероятность вытащить деталь, произведенную в первом
цехе - 10/40, во втором - 25/40, в третьем - 5/40. Сокращаем дроби,
получаем: 1/4, 5/8, 1/8.

По условию задачи в первом и третьем цеху вероятность получить детали
надлежащего качества 9/10, а во втором - 7/10 - это те самые условные
вероятности из второго пункта формулы.

Теперь перемножаем условные вероятности P(A|B) с вероятностями свершения
событий Вi и складываем их произведения.

Получатеся 1/4 * 9/10 + 1/8 * 9/10 + 5/8 * 7/10 = 31/40 =
0.775. Т.е. вероятность вытащить деталь надлежащего качества 0.775 или
75.5%.

** Задача 2
В тире имеются 5 различных по точности боя винтовок. Вероятности
попадания в мишень для данного стрелка соответственно равны 0,5; 0,55;
0,7; 0,75 и 0,4. Чему равна вероятность попадания в мишень, если стрелок
делает один выстрел из случайно выбранной винтовки?

*** Решение
У нас есть 5 винтовок. Шанс выбрать какую-то из них 1/5 (0.2) - это вероятность
события Вi, т.е. выбора винтовки.

Теперь надо перемножить все условные вероятности на вероятность выбора
какой-то винтовки и сложить их произведения.

(+ (* 0.2 0.5) (* 0.2 0.55) (* 0.2 0.7) (* 0.2 0.75) (* 0.2 0.4)) =
0.58. Это вероятность попасть в мишень из случайно выбранной винтовки.

** Задача 3

В пирамиде 5 винтовок, три из которых снабжены оптическим
прицелом. Вероятность того, что стрелок поразит мишень при выстреле из
винтовки с оптическим прицелом, равна 0,95; для винтовки без оптического
прицела эта вероятность равна 0,7. Найти вероятность того, что мишень
будет поражена, если стрелок производит один выстрел из наудачу взятой винтовки.

*** Решение
Теперь у нас есть вероятнсть 3/5 выстрелить из винтовки с оптическим
прицелом и 2/5 - с неоптическим.

Получаем (+ (* 0.6 0.95) ( * 0.7 0.4)) = 0.85 - это вероятность поразить
мишень из случайной винтовки.

* Условная вероятность
Это вероятность наступления события А, если произошло событие В.

Если P(A|B) = P(A) - т.е. вероятность наступления события А в следствие
наступления события В равна полной вероятности наступления А - то такие
события называются независимыми. Потому что А никак не зависит от В.

Так же важно знать, что P(A|B) != P(B|A).
То есть эти вероятности не взаимозаменяемы, хотя это
контринтуитивно.

Например, если протестировать всех зараженных лихорадкой
Денге, то тест даст положительный результат с вероятностью 90%. Но если
при тестировании рандомного человека получить положительный результат, то
есть только 15% вероятность, что он реально болен. Это происходит потому,
что в первом случе мы тестировали только больных, а во втором - больных и
здоровых.

Определение Колмогорова гласит, что P(A|B) = пересечению P(A) и P(B), деленным на P(B).

По-другому рассчитывают так: вероятность появления двух зависимых
событий равна произведению вероятности наступления одного из них на
условную вероятность другого, при условии, что первое событие произошло.

Т.е. P(AB) = P(A) * P(A|B) = P(B|A) * P(A) Отсюда формула условной вероятности, что
           P(AB)
P(A|B) =  ---------
           P(B).

** Задача 1

Из колоды в 36 карт последовательно извлекаются 2 карты. Найти
вероятность того, что вторая карта окажется червой, если до этого:
а) была извелечена черва
б) была извлечена карта другой масти

*** Решение
Разбираем задачу. Ясно, что вероятность вытащить вторую карту червой
зависит от того, вытащили ли черву ранее или нет.

36 карт - это сокращенная колода, она включает в себя карты от шестерок
до тузов. Это начит, что каждой масти там 9 карт.

a) Предполагаем, что сначала была извлечена черва. Осталось 35 карт всего и
   8 червы. В этом случае шанс вытащить черву составляет 8/35.
б) Преполагаем, что сначала была вытащена карта другой масти. В этом
   случае осталось всего 35 карт и 9 карт червы. Таким образом шанс
   вытащить черву следующей составляет 9/35.

То есть вероятность вытащить карту-черву выше в том случае, если до этого
мы вытащили не черву.

** Задача 2
В конверте находится 10 лотерейных билетов, среди которых 3
выигрышных. Из конверта последовательно извлекаются билеты. Найти
вероятности того, что
а) 2й извелеченный билет будет выигрышным, если первый был выигрышным
б) 3ий будет выгрышным, если предыдущие 2 были выигрышными
в) 4ый будет выигрышным, если предыдущие были выигрышными.

а) Если первый билет был выигрышным, то теперь у нас остается всего 9
билетов и 2 выгрышных. Итого вероятность 2/9.
б) Если вытащили 2 выигрышных билета, то остается всего 8 билетов и 1
выигрышный. Т.е. вероятность вытащить его следующим составляет 1/8.
в) Если три предыдущих билета были выигрышными, то вероятность вытащить
выигрышный четвертым = 0, поскольку всего выигрышных билетов было 3.

** Задача 3
В предыдущих двух задачах мы вычисляли вероятность свершения события в
том случае, если другое событие точно произошло. Но часто приходится
вычислять сначала вероятность того, что произойдет первое событие, а
затем в зависимости от этой вероятнсти вычислять вероятность того, что
произойдет второе событие.

Теперь усложняем.
Возвращемся к первой задаче, только теперь вычисляем вреоятность вытащить
вторую карту черву, ~если~ первая была червой, т.е. считаем ~вероятность
вытащить 2 карты-червы подряд~. Таким образом считаем, по
формуле.

Вероятность P(A) - вытащить первую черву - это 9/36,
т.е. 1/4. Вероятность вытащить вторую черву - это 8/35, как мы уже
считали. Теперь считаем (* 9/36 8/35) = 2/35. Т.е. шанс вытащить 2 червы
подряд = 2/35 или 0.057.

Теперь считаем шанс того, что сначала вытащим черву, а затем карту другой
масти: (* 9/36 27/35) = 27/140 или 0.1928.

** Задача 4
Усложняем задачу 2.

В конверте находится 10 лотерейных билетов, среди которых 3
выигрышных. Из конверта последовательно извлекаются билеты. Найти
вероятности того, что первые два вытащенных билета будут выигрышными.

Считаем вероятность вытащить первый выигрышный билет. Эта вероятность
3/10. Вероятность вытащить второй билет, как уже считали, 2/9. Тогда
(* 2/9 3/10) = 1/15 или 0.66.

Теперь считаем вероятность вытащить 3 выигрышных билета подряд:
(* 2/9 3/10 1/8) = 1/120 или 0.008.

** Задача 5

В урне 4 белых и 7 черных шаров. Из урны вытаскивают один за другим 2
шара, не возвращая их обратно. Найти вероятность того, что:

а) оба шара будут белыми
б) оба шара будут черными
в) сначала будет извлечен белый шар, а затем - черный.

а) Вероятность вытащить белвй шар составляет 4/11 в первый раз и 3/10 -
во второй. Итого вероятость вытащить два шара подряд (* 4/11 3/10) = 6/55
или 0.1090.

б) Вероятность вытащить первый черный шар составляет 7/11 и второй
6/10. Тогда вероятность вытащить 2 черных шара подряд составляет
(* 7/11 6/10) = 21/55 или 0.38.

в) Вероятность вытащить белый шар - 4/11, после этого вытащить черный -
7/10. Тогда вероятность вытащить белый шар, а затем черный это
(* 4/11 7/10) = 14/55 или 0.25.

Таким образом получается, что наиболее вероятный исход - это вытащить 2
черных шара подряд, это аж 38% против 10% вероятности вытащить 2 белых
подряд или 25% вероятности вытащить сначала белый, а потом черный.

* Теорема Байеса
Формула Байеса позволяет переставить причину и следствие: т.е. по уже
свершившемуся событию представить, какой причиной оно было
вызвано. События, отражающие действия "причин" называются ~гипотезами~,
т.к. они ~предполагаемые~ события, повлекшие за собой другие события.

Безусловную вероятность свершения события называют ~априорной~ -
т.е. насколько вообще вероятно свершение события. А условную - с учетом
произшедшего другого события - называют ~апостериорной~.


            P(B|A) P(A)
 P(A|B) =  --------------
               P(B)

Формула теоремы байеса звучит так:
вероятность гипотезы А при наступлении события В - обозначается как
P(A|B) - равна произведению вероятности наступления события В при
истинности гипотезы А - обозначается как P(B|A) - на априорную
вероятность гипотезы А - P(A) - деленному на полную вероятность события
В - обозначается как P(B).

** Пример 1
Есть 3 рабочих. У первого вероятность заводского брака  = 0.9 (т.е. 9 из
10 деталей бракованные), у второго - 0.5, у третьего - 0.2. Первый
изготовил 800 деталей, второй - 600 деталей, третий 900
деталей. Начальник цеха случайно выбирает одну из деталей и она
оказывается бракованной. С какой вероятностью эту деталь изготовил третий
рабочий?


Начинаем считать. Событие В - это бракованная деталь. Событие Аi - это
деталь произвел рабочий Рi.

По формуле полной вероятности считаем вероятность вытащить бракованную
деталь в принципе.

Всего деталей 2300.
Теперь считаем (+ (* 800/2300 0.9) (* 600/2300 0.5) (* 900/2300 0.2)) = 0.52.
Это вероятность вытащить бракованную деталь в принцпе, т.е. P(B) в
формуле.

Предположим, что этот риск реализовался. Теперь смотрим на формулу
условной вероятности: P(AB) = P(A) * P(A|B) = P(B|A) * P(A). Где P(A) -
это вероятность вытащить любую деталь от третьего рабочего - это 900/2300, а
условная вероятность получить брак, если деталь была выпущена третьим
рабочим, составляет 0.2. Теперь считаем (* 900/2300 0.2) = 0.078. Таким
образом мы высчитали числитель и знаменатель дроби в формуле
Байеса. Теперь считаем (/ 0.078 0.52) = 0.15.

** Задача 1
Из 30 стрелков 12 попадает в цель с вероятностью 0,6, 8 - с вероятностью
0,5 и 10 – с вероятностью 0,7. Наудачу выбранный стрелок произвел
выстрел, поразив цель. К какой из групп вероятнее всего принадлежал этот
стрелок?

*** Решение
Сначала по формуле полной вероятности считаем вероятность, с которой
кто-то, неважно из какой группы, поразит цель:

(+ (* 0.6 12/30) (* 0.5 8/30) (* 0.7 10/30)) = 0.60.

Теперь для каждого из стрелков считаем апостериорную вероятность того,
что кто-то поразил из них цель - мы знаем, что цель поражена с
вероятностью 60%.

1. (/ (* 0.6 12/30) 0.60) = 0.4
2. (/ (* 0.5 8/30) 0.60) = 0.22
3. (/ (* 0.7 10/30) 0.60) = 0.38

Получается, что скорее всего мишень поразил первый стрелок.

** Задача 2
В первой и в третьей группах одинаковое число студентов, а во второй – в
1,5 раза меньше, чем в первой. Количество отличников составляет 9% в
первой, 4% во второй и 6% в третьей группе.

а) Найти вероятность того, что случайно вызванный студент – отличник.

б) Случайно вызванный студент оказался отличником. Найти вероятность
того, что студент учится в третьей группе.

*** Решение
Считаем, что в первой и третьей группах по 20 студентов, а во второй - 5.
По формуле полной вероятности считаем вероятность вызова отличника:
(+ (* 0.9 20/45) (* 0.6 20/45) (* 0.4 5/45)) = 0.71

Теперь считаем вероятность, что отличник оказался из третьей группы:
(/ (* 0.4 5/45) 0.71) = 0.062, т.е. примерно 6.2%

* Задачи на повторение
Здесь берем задачи на все три темы: формула полной вероятности, формула
условной вероятности и формула Байеса. Надо самостоятельно определить, к
какой формуле какая задача подходит и решить.

** Задача 1
Из 1000 ламп 380 принадлежат к 1 партии, 270 – ко второй партии,
остальные к третьей. В первой партии 4% брака, во второй - 3%, в третьей
– 6%. Наудачу выбирается одна лампа. Определить вероятность того, что
выбранная лампа – бракованная.

*** Решение
Это задача на нахождение полной вероятности, поскольку у нас только 1
событие - вытаскивание бракованной лампы.

Считаем по формуле:
(+ (* 380/1000 0.04) (* 270/1000 0.03) (* 350/1000 0.06)) = 0.044
т.е. около 4.4%

** Задача 2
Сотрудники отдела маркетинга полагают, что в ближайшее время ожидается
рост спроса на продукцию фирмы. Вероятность этого они оценивают в
80%. Консультационная фирма, занимающаяся прогнозом рыночной ситуации,
подтвердила предположение о росте спроса. Положительные прогнозы
консультационной фирмы сбываются с вероятностью 95%, а отрицательные – с
вероятностью 99%. Какова вероятность того, что рост спроса действительно
произойдет?

*** Решение
Это опять задача на формулу полной вероятности, поскольку событие не
зависит от условий.

Событие А - это взлет спроса. Маркетологи утверждают, что спрос
произойдет с вероятностью 0.8, и что не произойдет с вероятностью
0.2. Т.е. теперь у нас есть вероятности что событие А произойдет и не
произойдет.

И есть консалтиговая фирма, у которой сбывается 0.95 положительных
прогнозов и 0.99 отрицательных. Считаем по формуле:
(+ (* 0.8 0.95) (* 0.2 0.99)) = 0.958, т.е. 95.8%

** Задача 3
В группе спортсменов лыжников в 2 раза больше, чем бегунов, а
бегунов в 3 раза больше, чем велосипедистов. Вероятность выполнить норму
для лыжника 0,9, для бегуна 0,75, для велосипедиста - 0,8. Найти
вероятность того, что спортсмен, выбранный наугад, выполнит норму.

*** Решение
Итак, сначала считаем вероятность выбрать какого-то конкретного
спортсмена: велосепедиста, бегуна или лижника.
Считаем, что у нас 10 велосипедистов, 30 бегунов и 60 лыжников, в сего
спортсменов, следовательно, 100.

Теперь по формуле волной вероятности считаем
(+ (* 0.8 10/100) (* 0.75 30/100) (* 0.9 60/100)) = 0.845 = 84.5%

** Задача 4.
В двух урнах находится соответственно 4 и 5 белых и 6 и 3
чёрных шаров. Из каждой урны наудачу извлекается один шар, а затем из
этих двух наудачу берется один. Какова вероятность, что это будет белый
шар?
